/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc2x3javatoolbox.ifc2x3tc1;
/**
 * This is a default implementation of the entity IfcMaterialLayerSetUsage<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcMaterialLayerSetUsage extends InternalAccessClass implements ClassInterface, IfcMaterialSelect
{
	private static final String[] nonInverseAttributes = new String[]{"IfcMaterialLayerSet","IfcLayerSetDirectionEnum","IfcDirectionSenseEnum","IfcLengthMeasure"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** ForLayerSet is an DEMANDED attribute - may not be null**/
	protected IfcMaterialLayerSet ForLayerSet;
	/** LayerSetDirection is an DEMANDED attribute - may not be null**/
	protected IfcLayerSetDirectionEnum LayerSetDirection;
	/** DirectionSense is an DEMANDED attribute - may not be null**/
	protected IfcDirectionSenseEnum DirectionSense;
	/** OffsetFromReferenceLine is an DEMANDED attribute - may not be null**/
	protected IfcLengthMeasure OffsetFromReferenceLine;
	/**
	* The default constructor.
	**/
	public IfcMaterialLayerSetUsage(){}

	private static final String[] attributes = new String[]{"ForLayerSet","LayerSetDirection"
	,"DirectionSense","OffsetFromReferenceLine"};

	public String[] getAttributes() {
		return IfcMaterialLayerSetUsage.attributes;
	}

	/**
	* Constructs a new IfcMaterialLayerSetUsage object using the given parameters.
	*
	* @param ForLayerSet DEMANDED parameter of type IfcMaterialLayerSet - may not be null.
	* @param LayerSetDirection DEMANDED parameter of type IfcLayerSetDirectionEnum - may not be null.
	* @param DirectionSense DEMANDED parameter of type IfcDirectionSenseEnum - may not be null.
	* @param OffsetFromReferenceLine DEMANDED parameter of type IfcLengthMeasure - may not be null.
	**/
	public IfcMaterialLayerSetUsage(IfcMaterialLayerSet ForLayerSet, IfcLayerSetDirectionEnum LayerSetDirection, IfcDirectionSenseEnum DirectionSense, IfcLengthMeasure OffsetFromReferenceLine)
	{
		this.ForLayerSet = ForLayerSet;
		this.LayerSetDirection = LayerSetDirection;
		this.DirectionSense = DirectionSense;
		this.OffsetFromReferenceLine = OffsetFromReferenceLine;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcMaterialLayerSetUsage object using the given parameters.
	*
	* @param ForLayerSet DEMANDED parameter of type IfcMaterialLayerSet - may not be null.
	* @param LayerSetDirection DEMANDED parameter of type IfcLayerSetDirectionEnum - may not be null.
	* @param DirectionSense DEMANDED parameter of type IfcDirectionSenseEnum - may not be null.
	* @param OffsetFromReferenceLine DEMANDED parameter of type IfcLengthMeasure - may not be null.
	**/
	public void setParameters(IfcMaterialLayerSet ForLayerSet, IfcLayerSetDirectionEnum LayerSetDirection, IfcDirectionSenseEnum DirectionSense, IfcLengthMeasure OffsetFromReferenceLine)
	{
		this.ForLayerSet = ForLayerSet;
		this.LayerSetDirection = LayerSetDirection;
		this.DirectionSense = DirectionSense;
		this.OffsetFromReferenceLine = OffsetFromReferenceLine;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.ForLayerSet = (IfcMaterialLayerSet) parameters.get(0);
		this.LayerSetDirection = (IfcLayerSetDirectionEnum) parameters.get(1);
		this.DirectionSense = (IfcDirectionSenseEnum) parameters.get(2);
		this.OffsetFromReferenceLine = (IfcLengthMeasure) parameters.get(3);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		listenerList = null;
	}

	private void resolveInverses()
	{
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcMaterialLayerSetUsage.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCMATERIALLAYERSETUSAGE(");
		if(getRedefinedDerivedAttributeTypes().contains("ForLayerSet")) stepString = stepString.concat("*,");
		else{
		if(this.ForLayerSet != null)		stepString = stepString.concat(((RootInterface)this.ForLayerSet).getStepParameter(IfcMaterialLayerSet.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("LayerSetDirection")) stepString = stepString.concat("*,");
		else{
		if(this.LayerSetDirection != null)		stepString = stepString.concat(((RootInterface)this.LayerSetDirection).getStepParameter(IfcLayerSetDirectionEnum.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("DirectionSense")) stepString = stepString.concat("*,");
		else{
		if(this.DirectionSense != null)		stepString = stepString.concat(((RootInterface)this.DirectionSense).getStepParameter(IfcDirectionSenseEnum.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("OffsetFromReferenceLine")) stepString = stepString.concat("*);");
		else{
		if(this.OffsetFromReferenceLine != null)		stepString = stepString.concat(((RootInterface)this.OffsetFromReferenceLine).getStepParameter(IfcLengthMeasure.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method sets the ForLayerSet attribute to the given value.
	*
	* @param ForLayerSet OPTIONAL value to set
	**/
	public void setForLayerSet(IfcMaterialLayerSet ForLayerSet)
	{
		this.ForLayerSet = ForLayerSet;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the ForLayerSet attribute.
	*
	* @return the value of ForLayerSet
	/**/
	public IfcMaterialLayerSet getForLayerSet()
	{
		return this.ForLayerSet;
	}

	/**
	* This method sets the LayerSetDirection attribute to the given value.
	*
	* @param LayerSetDirection OPTIONAL value to set
	**/
	public void setLayerSetDirection(IfcLayerSetDirectionEnum LayerSetDirection)
	{
		this.LayerSetDirection = LayerSetDirection;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the LayerSetDirection attribute.
	*
	* @return the value of LayerSetDirection
	/**/
	public IfcLayerSetDirectionEnum getLayerSetDirection()
	{
		return this.LayerSetDirection;
	}

	/**
	* This method sets the DirectionSense attribute to the given value.
	*
	* @param DirectionSense OPTIONAL value to set
	**/
	public void setDirectionSense(IfcDirectionSenseEnum DirectionSense)
	{
		this.DirectionSense = DirectionSense;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the DirectionSense attribute.
	*
	* @return the value of DirectionSense
	/**/
	public IfcDirectionSenseEnum getDirectionSense()
	{
		return this.DirectionSense;
	}

	/**
	* This method sets the OffsetFromReferenceLine attribute to the given value.
	*
	* @param OffsetFromReferenceLine OPTIONAL value to set
	**/
	public void setOffsetFromReferenceLine(IfcLengthMeasure OffsetFromReferenceLine)
	{
		this.OffsetFromReferenceLine = OffsetFromReferenceLine;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the OffsetFromReferenceLine attribute.
	*
	* @return the value of OffsetFromReferenceLine
	/**/
	public IfcLengthMeasure getOffsetFromReferenceLine()
	{
		return this.OffsetFromReferenceLine;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	public Object clone()
	{
		IfcMaterialLayerSetUsage ifcMaterialLayerSetUsage = new IfcMaterialLayerSetUsage();
		if(this.ForLayerSet != null)
			ifcMaterialLayerSetUsage.setForLayerSet((IfcMaterialLayerSet)this.ForLayerSet.clone());
		if(this.LayerSetDirection != null)
			ifcMaterialLayerSetUsage.setLayerSetDirection((IfcLayerSetDirectionEnum)this.LayerSetDirection.clone());
		if(this.DirectionSense != null)
			ifcMaterialLayerSetUsage.setDirectionSense((IfcDirectionSenseEnum)this.DirectionSense.clone());
		if(this.OffsetFromReferenceLine != null)
			ifcMaterialLayerSetUsage.setOffsetFromReferenceLine((IfcLengthMeasure)this.OffsetFromReferenceLine.clone());
		return ifcMaterialLayerSetUsage;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcMaterialLayerSetUsage ifcMaterialLayerSetUsage = new IfcMaterialLayerSetUsage();
		if(this.ForLayerSet != null)
			ifcMaterialLayerSetUsage.setForLayerSet(this.ForLayerSet);
		if(this.LayerSetDirection != null)
			ifcMaterialLayerSetUsage.setLayerSetDirection(this.LayerSetDirection);
		if(this.DirectionSense != null)
			ifcMaterialLayerSetUsage.setDirectionSense(this.DirectionSense);
		if(this.OffsetFromReferenceLine != null)
			ifcMaterialLayerSetUsage.setOffsetFromReferenceLine(this.OffsetFromReferenceLine);
		return ifcMaterialLayerSetUsage;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
