/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc2x3javatoolbox.ifc2x3tc1;
/**
 * This is a default implementation of the entity IfcReinforcingBar<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcReinforcingBar extends IfcReinforcingElement implements ClassInterface
{
	private static final String[] nonInverseAttributes = new String[]{"IfcGloballyUniqueId","IfcOwnerHistory","IfcLabel","IfcText","IfcLabel","IfcObjectPlacement","IfcProductRepresentation","IfcIdentifier","IfcLabel","IfcPositiveLengthMeasure","IfcAreaMeasure","IfcPositiveLengthMeasure","IfcReinforcingBarRoleEnum","IfcReinforcingBarSurfaceEnum"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** NominalDiameter is an DEMANDED attribute - may not be null**/
	protected IfcPositiveLengthMeasure NominalDiameter;
	/** CrossSectionArea is an DEMANDED attribute - may not be null**/
	protected IfcAreaMeasure CrossSectionArea;
	/** BarLength is an OPTIONAL attribute**/
	protected IfcPositiveLengthMeasure BarLength;
	/** BarRole is an DEMANDED attribute - may not be null**/
	protected IfcReinforcingBarRoleEnum BarRole;
	/** BarSurface is an OPTIONAL attribute**/
	protected IfcReinforcingBarSurfaceEnum BarSurface;
	/**
	* The default constructor.
	**/
	public IfcReinforcingBar(){}

	private static final String[] attributes = new String[]{"GlobalId","OwnerHistory","Name","Description"
			,"ObjectType","ObjectPlacement","Representation","Tag","SteelGrade","NominalDiameter"
	,"CrossSectionArea","BarLength","BarRole","BarSurface"};

	public String[] getAttributes() {
		return IfcReinforcingBar.attributes;
	}

	/**
	* Constructs a new IfcReinforcingBar object using the given parameters.
	*
	* @param GlobalId DEMANDED parameter of type IfcGloballyUniqueId - may not be null.
	* @param OwnerHistory DEMANDED parameter of type IfcOwnerHistory - may not be null.
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param Description OPTIONAL parameter of type IfcText
	* @param ObjectType OPTIONAL parameter of type IfcLabel
	* @param ObjectPlacement OPTIONAL parameter of type IfcObjectPlacement
	* @param Representation OPTIONAL parameter of type IfcProductRepresentation
	* @param Tag OPTIONAL parameter of type IfcIdentifier
	* @param SteelGrade OPTIONAL parameter of type IfcLabel
	* @param NominalDiameter DEMANDED parameter of type IfcPositiveLengthMeasure - may not be null.
	* @param CrossSectionArea DEMANDED parameter of type IfcAreaMeasure - may not be null.
	* @param BarLength OPTIONAL parameter of type IfcPositiveLengthMeasure
	* @param BarRole DEMANDED parameter of type IfcReinforcingBarRoleEnum - may not be null.
	* @param BarSurface OPTIONAL parameter of type IfcReinforcingBarSurfaceEnum
	**/
	public IfcReinforcingBar(IfcGloballyUniqueId GlobalId, IfcOwnerHistory OwnerHistory, IfcLabel Name, IfcText Description, IfcLabel ObjectType, IfcObjectPlacement ObjectPlacement, IfcProductRepresentation Representation, IfcIdentifier Tag, IfcLabel SteelGrade, IfcPositiveLengthMeasure NominalDiameter, IfcAreaMeasure CrossSectionArea, IfcPositiveLengthMeasure BarLength, IfcReinforcingBarRoleEnum BarRole, IfcReinforcingBarSurfaceEnum BarSurface)
	{
		this.GlobalId = GlobalId;
		this.OwnerHistory = OwnerHistory;
		this.Name = Name;
		this.Description = Description;
		this.ObjectType = ObjectType;
		this.ObjectPlacement = ObjectPlacement;
		this.Representation = Representation;
		this.Tag = Tag;
		this.SteelGrade = SteelGrade;
		this.NominalDiameter = NominalDiameter;
		this.CrossSectionArea = CrossSectionArea;
		this.BarLength = BarLength;
		this.BarRole = BarRole;
		this.BarSurface = BarSurface;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcReinforcingBar object using the given parameters.
	*
	* @param GlobalId DEMANDED parameter of type IfcGloballyUniqueId - may not be null.
	* @param OwnerHistory DEMANDED parameter of type IfcOwnerHistory - may not be null.
	* @param Name OPTIONAL parameter of type IfcLabel
	* @param Description OPTIONAL parameter of type IfcText
	* @param ObjectType OPTIONAL parameter of type IfcLabel
	* @param ObjectPlacement OPTIONAL parameter of type IfcObjectPlacement
	* @param Representation OPTIONAL parameter of type IfcProductRepresentation
	* @param Tag OPTIONAL parameter of type IfcIdentifier
	* @param SteelGrade OPTIONAL parameter of type IfcLabel
	* @param NominalDiameter DEMANDED parameter of type IfcPositiveLengthMeasure - may not be null.
	* @param CrossSectionArea DEMANDED parameter of type IfcAreaMeasure - may not be null.
	* @param BarLength OPTIONAL parameter of type IfcPositiveLengthMeasure
	* @param BarRole DEMANDED parameter of type IfcReinforcingBarRoleEnum - may not be null.
	* @param BarSurface OPTIONAL parameter of type IfcReinforcingBarSurfaceEnum
	**/
	public void setParameters(IfcGloballyUniqueId GlobalId, IfcOwnerHistory OwnerHistory, IfcLabel Name, IfcText Description, IfcLabel ObjectType, IfcObjectPlacement ObjectPlacement, IfcProductRepresentation Representation, IfcIdentifier Tag, IfcLabel SteelGrade, IfcPositiveLengthMeasure NominalDiameter, IfcAreaMeasure CrossSectionArea, IfcPositiveLengthMeasure BarLength, IfcReinforcingBarRoleEnum BarRole, IfcReinforcingBarSurfaceEnum BarSurface)
	{
		this.GlobalId = GlobalId;
		this.OwnerHistory = OwnerHistory;
		this.Name = Name;
		this.Description = Description;
		this.ObjectType = ObjectType;
		this.ObjectPlacement = ObjectPlacement;
		this.Representation = Representation;
		this.Tag = Tag;
		this.SteelGrade = SteelGrade;
		this.NominalDiameter = NominalDiameter;
		this.CrossSectionArea = CrossSectionArea;
		this.BarLength = BarLength;
		this.BarRole = BarRole;
		this.BarSurface = BarSurface;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.GlobalId = (IfcGloballyUniqueId) parameters.get(0);
		this.OwnerHistory = (IfcOwnerHistory) parameters.get(1);
		this.Name = (IfcLabel) parameters.get(2);
		this.Description = (IfcText) parameters.get(3);
		this.ObjectType = (IfcLabel) parameters.get(4);
		this.ObjectPlacement = (IfcObjectPlacement) parameters.get(5);
		this.Representation = (IfcProductRepresentation) parameters.get(6);
		this.Tag = (IfcIdentifier) parameters.get(7);
		this.SteelGrade = (IfcLabel) parameters.get(8);
		this.NominalDiameter = (IfcPositiveLengthMeasure) parameters.get(9);
		this.CrossSectionArea = (IfcAreaMeasure) parameters.get(10);
		this.BarLength = (IfcPositiveLengthMeasure) parameters.get(11);
		this.BarRole = (IfcReinforcingBarRoleEnum) parameters.get(12);
		this.BarSurface = (IfcReinforcingBarSurfaceEnum) parameters.get(13);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		 super.destruct();
		listenerList = null;
	}

	private void resolveInverses()
	{
		if(ObjectPlacement != null)
		{
				if(ObjectPlacement.PlacesObject_Inverse == null)
				{
					ObjectPlacement.PlacesObject_Inverse = new SET<IfcProduct>();
				}
				ObjectPlacement.PlacesObject_Inverse.add(this);
		}
		if(Representation != null)
		{
				if(Representation instanceof IfcProductDefinitionShape)
				{
				if(((IfcProductDefinitionShape)Representation).ShapeOfProduct_Inverse == null)
				{
					((IfcProductDefinitionShape)Representation).ShapeOfProduct_Inverse = new SET<IfcProduct>();
				}
				((IfcProductDefinitionShape)Representation).ShapeOfProduct_Inverse.add(this);
				}
		}
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcReinforcingBar.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCREINFORCINGBAR(");
		if(getRedefinedDerivedAttributeTypes().contains("GlobalId")) stepString = stepString.concat("*,");
		else{
		if(this.GlobalId != null)		stepString = stepString.concat(((RootInterface)this.GlobalId).getStepParameter(IfcGloballyUniqueId.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("OwnerHistory")) stepString = stepString.concat("*,");
		else{
		if(this.OwnerHistory != null)		stepString = stepString.concat(((RootInterface)this.OwnerHistory).getStepParameter(IfcOwnerHistory.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Name")) stepString = stepString.concat("*,");
		else{
		if(this.Name != null)		stepString = stepString.concat(((RootInterface)this.Name).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Description")) stepString = stepString.concat("*,");
		else{
		if(this.Description != null)		stepString = stepString.concat(((RootInterface)this.Description).getStepParameter(IfcText.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("ObjectType")) stepString = stepString.concat("*,");
		else{
		if(this.ObjectType != null)		stepString = stepString.concat(((RootInterface)this.ObjectType).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("ObjectPlacement")) stepString = stepString.concat("*,");
		else{
		if(this.ObjectPlacement != null)		stepString = stepString.concat(((RootInterface)this.ObjectPlacement).getStepParameter(IfcObjectPlacement.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Representation")) stepString = stepString.concat("*,");
		else{
		if(this.Representation != null)		stepString = stepString.concat(((RootInterface)this.Representation).getStepParameter(IfcProductRepresentation.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Tag")) stepString = stepString.concat("*,");
		else{
		if(this.Tag != null)		stepString = stepString.concat(((RootInterface)this.Tag).getStepParameter(IfcIdentifier.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("SteelGrade")) stepString = stepString.concat("*,");
		else{
		if(this.SteelGrade != null)		stepString = stepString.concat(((RootInterface)this.SteelGrade).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("NominalDiameter")) stepString = stepString.concat("*,");
		else{
		if(this.NominalDiameter != null)		stepString = stepString.concat(((RootInterface)this.NominalDiameter).getStepParameter(IfcPositiveLengthMeasure.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("CrossSectionArea")) stepString = stepString.concat("*,");
		else{
		if(this.CrossSectionArea != null)		stepString = stepString.concat(((RootInterface)this.CrossSectionArea).getStepParameter(IfcAreaMeasure.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("BarLength")) stepString = stepString.concat("*,");
		else{
		if(this.BarLength != null)		stepString = stepString.concat(((RootInterface)this.BarLength).getStepParameter(IfcPositiveLengthMeasure.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("BarRole")) stepString = stepString.concat("*,");
		else{
		if(this.BarRole != null)		stepString = stepString.concat(((RootInterface)this.BarRole).getStepParameter(IfcReinforcingBarRoleEnum.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("BarSurface")) stepString = stepString.concat("*);");
		else{
		if(this.BarSurface != null)		stepString = stepString.concat(((RootInterface)this.BarSurface).getStepParameter(IfcReinforcingBarSurfaceEnum.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method sets the NominalDiameter attribute to the given value.
	*
	* @param NominalDiameter OPTIONAL value to set
	**/
	public void setNominalDiameter(IfcPositiveLengthMeasure NominalDiameter)
	{
		this.NominalDiameter = NominalDiameter;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the NominalDiameter attribute.
	*
	* @return the value of NominalDiameter
	/**/
	public IfcPositiveLengthMeasure getNominalDiameter()
	{
		return this.NominalDiameter;
	}

	/**
	* This method sets the CrossSectionArea attribute to the given value.
	*
	* @param CrossSectionArea OPTIONAL value to set
	**/
	public void setCrossSectionArea(IfcAreaMeasure CrossSectionArea)
	{
		this.CrossSectionArea = CrossSectionArea;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the CrossSectionArea attribute.
	*
	* @return the value of CrossSectionArea
	/**/
	public IfcAreaMeasure getCrossSectionArea()
	{
		return this.CrossSectionArea;
	}

	/**
	* This method sets the BarLength attribute to the given value.
	*
	* @param BarLength DEMANDED value to set - may not be null
	**/
	public void setBarLength(IfcPositiveLengthMeasure BarLength)
	{
		this.BarLength = BarLength;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the BarLength attribute.
	*
	* @return the value of BarLength
	/**/
	public IfcPositiveLengthMeasure getBarLength()
	{
		return this.BarLength;
	}

	/**
	* This method sets the BarRole attribute to the given value.
	*
	* @param BarRole OPTIONAL value to set
	**/
	public void setBarRole(IfcReinforcingBarRoleEnum BarRole)
	{
		this.BarRole = BarRole;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the BarRole attribute.
	*
	* @return the value of BarRole
	/**/
	public IfcReinforcingBarRoleEnum getBarRole()
	{
		return this.BarRole;
	}

	/**
	* This method sets the BarSurface attribute to the given value.
	*
	* @param BarSurface DEMANDED value to set - may not be null
	**/
	public void setBarSurface(IfcReinforcingBarSurfaceEnum BarSurface)
	{
		this.BarSurface = BarSurface;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the BarSurface attribute.
	*
	* @return the value of BarSurface
	/**/
	public IfcReinforcingBarSurfaceEnum getBarSurface()
	{
		return this.BarSurface;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	public Object clone()
	{
		IfcReinforcingBar ifcReinforcingBar = new IfcReinforcingBar();
		if(this.GlobalId != null)
			ifcReinforcingBar.setGlobalId((IfcGloballyUniqueId)this.GlobalId.clone());
		if(this.OwnerHistory != null)
			ifcReinforcingBar.setOwnerHistory((IfcOwnerHistory)this.OwnerHistory.clone());
		if(this.Name != null)
			ifcReinforcingBar.setName((IfcLabel)this.Name.clone());
		if(this.Description != null)
			ifcReinforcingBar.setDescription((IfcText)this.Description.clone());
		if(this.ObjectType != null)
			ifcReinforcingBar.setObjectType((IfcLabel)this.ObjectType.clone());
		if(this.ObjectPlacement != null)
			ifcReinforcingBar.setObjectPlacement((IfcObjectPlacement)this.ObjectPlacement.clone());
		if(this.Representation != null)
			ifcReinforcingBar.setRepresentation((IfcProductRepresentation)this.Representation.clone());
		if(this.Tag != null)
			ifcReinforcingBar.setTag((IfcIdentifier)this.Tag.clone());
		if(this.SteelGrade != null)
			ifcReinforcingBar.setSteelGrade((IfcLabel)this.SteelGrade.clone());
		if(this.NominalDiameter != null)
			ifcReinforcingBar.setNominalDiameter((IfcPositiveLengthMeasure)this.NominalDiameter.clone());
		if(this.CrossSectionArea != null)
			ifcReinforcingBar.setCrossSectionArea((IfcAreaMeasure)this.CrossSectionArea.clone());
		if(this.BarLength != null)
			ifcReinforcingBar.setBarLength((IfcPositiveLengthMeasure)this.BarLength.clone());
		if(this.BarRole != null)
			ifcReinforcingBar.setBarRole((IfcReinforcingBarRoleEnum)this.BarRole.clone());
		if(this.BarSurface != null)
			ifcReinforcingBar.setBarSurface((IfcReinforcingBarSurfaceEnum)this.BarSurface.clone());
		return ifcReinforcingBar;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcReinforcingBar ifcReinforcingBar = new IfcReinforcingBar();
		if(this.GlobalId != null)
			ifcReinforcingBar.setGlobalId(this.GlobalId);
		if(this.OwnerHistory != null)
			ifcReinforcingBar.setOwnerHistory(this.OwnerHistory);
		if(this.Name != null)
			ifcReinforcingBar.setName(this.Name);
		if(this.Description != null)
			ifcReinforcingBar.setDescription(this.Description);
		if(this.ObjectType != null)
			ifcReinforcingBar.setObjectType(this.ObjectType);
		if(this.ObjectPlacement != null)
			ifcReinforcingBar.setObjectPlacement(this.ObjectPlacement);
		if(this.Representation != null)
			ifcReinforcingBar.setRepresentation(this.Representation);
		if(this.Tag != null)
			ifcReinforcingBar.setTag(this.Tag);
		if(this.SteelGrade != null)
			ifcReinforcingBar.setSteelGrade(this.SteelGrade);
		if(this.NominalDiameter != null)
			ifcReinforcingBar.setNominalDiameter(this.NominalDiameter);
		if(this.CrossSectionArea != null)
			ifcReinforcingBar.setCrossSectionArea(this.CrossSectionArea);
		if(this.BarLength != null)
			ifcReinforcingBar.setBarLength(this.BarLength);
		if(this.BarRole != null)
			ifcReinforcingBar.setBarRole(this.BarRole);
		if(this.BarSurface != null)
			ifcReinforcingBar.setBarSurface(this.BarSurface);
		return ifcReinforcingBar;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
