/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc2x3javatoolbox.ifc2x3tc1;
/**
 * This is a default implementation of the entity IfcRoundedRectangleProfileDef<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcRoundedRectangleProfileDef extends IfcRectangleProfileDef implements ClassInterface
{
	private static final String[] nonInverseAttributes = new String[]{"IfcProfileTypeEnum","IfcLabel","IfcAxis2Placement2D","IfcPositiveLengthMeasure","IfcPositiveLengthMeasure","IfcPositiveLengthMeasure"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** RoundingRadius is an DEMANDED attribute - may not be null**/
	protected IfcPositiveLengthMeasure RoundingRadius;
	/**
	* The default constructor.
	**/
	public IfcRoundedRectangleProfileDef(){}

	private static final String[] attributes = new String[]{"ProfileType","ProfileName","Position","XDim"
			,"YDim","RoundingRadius"};

	public String[] getAttributes() {
		return IfcRoundedRectangleProfileDef.attributes;
	}

	/**
	* Constructs a new IfcRoundedRectangleProfileDef object using the given parameters.
	*
	* @param ProfileType DEMANDED parameter of type IfcProfileTypeEnum - may not be null.
	* @param ProfileName OPTIONAL parameter of type IfcLabel
	* @param Position DEMANDED parameter of type IfcAxis2Placement2D - may not be null.
	* @param XDim DEMANDED parameter of type IfcPositiveLengthMeasure - may not be null.
	* @param YDim DEMANDED parameter of type IfcPositiveLengthMeasure - may not be null.
	* @param RoundingRadius DEMANDED parameter of type IfcPositiveLengthMeasure - may not be null.
	**/
	public IfcRoundedRectangleProfileDef(IfcProfileTypeEnum ProfileType, IfcLabel ProfileName, IfcAxis2Placement2D Position, IfcPositiveLengthMeasure XDim, IfcPositiveLengthMeasure YDim, IfcPositiveLengthMeasure RoundingRadius)
	{
		this.ProfileType = ProfileType;
		this.ProfileName = ProfileName;
		this.Position = Position;
		this.XDim = XDim;
		this.YDim = YDim;
		this.RoundingRadius = RoundingRadius;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcRoundedRectangleProfileDef object using the given parameters.
	*
	* @param ProfileType DEMANDED parameter of type IfcProfileTypeEnum - may not be null.
	* @param ProfileName OPTIONAL parameter of type IfcLabel
	* @param Position DEMANDED parameter of type IfcAxis2Placement2D - may not be null.
	* @param XDim DEMANDED parameter of type IfcPositiveLengthMeasure - may not be null.
	* @param YDim DEMANDED parameter of type IfcPositiveLengthMeasure - may not be null.
	* @param RoundingRadius DEMANDED parameter of type IfcPositiveLengthMeasure - may not be null.
	**/
	public void setParameters(IfcProfileTypeEnum ProfileType, IfcLabel ProfileName, IfcAxis2Placement2D Position, IfcPositiveLengthMeasure XDim, IfcPositiveLengthMeasure YDim, IfcPositiveLengthMeasure RoundingRadius)
	{
		this.ProfileType = ProfileType;
		this.ProfileName = ProfileName;
		this.Position = Position;
		this.XDim = XDim;
		this.YDim = YDim;
		this.RoundingRadius = RoundingRadius;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.ProfileType = (IfcProfileTypeEnum) parameters.get(0);
		this.ProfileName = (IfcLabel) parameters.get(1);
		this.Position = (IfcAxis2Placement2D) parameters.get(2);
		this.XDim = (IfcPositiveLengthMeasure) parameters.get(3);
		this.YDim = (IfcPositiveLengthMeasure) parameters.get(4);
		this.RoundingRadius = (IfcPositiveLengthMeasure) parameters.get(5);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		 super.destruct();
		listenerList = null;
	}

	private void resolveInverses()
	{
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcRoundedRectangleProfileDef.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCROUNDEDRECTANGLEPROFILEDEF(");
		if(getRedefinedDerivedAttributeTypes().contains("ProfileType")) stepString = stepString.concat("*,");
		else{
		if(this.ProfileType != null)		stepString = stepString.concat(((RootInterface)this.ProfileType).getStepParameter(IfcProfileTypeEnum.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("ProfileName")) stepString = stepString.concat("*,");
		else{
		if(this.ProfileName != null)		stepString = stepString.concat(((RootInterface)this.ProfileName).getStepParameter(IfcLabel.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("Position")) stepString = stepString.concat("*,");
		else{
		if(this.Position != null)		stepString = stepString.concat(((RootInterface)this.Position).getStepParameter(IfcAxis2Placement2D.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("XDim")) stepString = stepString.concat("*,");
		else{
		if(this.XDim != null)		stepString = stepString.concat(((RootInterface)this.XDim).getStepParameter(IfcPositiveLengthMeasure.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("YDim")) stepString = stepString.concat("*,");
		else{
		if(this.YDim != null)		stepString = stepString.concat(((RootInterface)this.YDim).getStepParameter(IfcPositiveLengthMeasure.class.isInterface())+",");
		else		stepString = stepString.concat("$,");
		}
		if(getRedefinedDerivedAttributeTypes().contains("RoundingRadius")) stepString = stepString.concat("*);");
		else{
		if(this.RoundingRadius != null)		stepString = stepString.concat(((RootInterface)this.RoundingRadius).getStepParameter(IfcPositiveLengthMeasure.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method sets the RoundingRadius attribute to the given value.
	*
	* @param RoundingRadius OPTIONAL value to set
	**/
	public void setRoundingRadius(IfcPositiveLengthMeasure RoundingRadius)
	{
		this.RoundingRadius = RoundingRadius;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the RoundingRadius attribute.
	*
	* @return the value of RoundingRadius
	/**/
	public IfcPositiveLengthMeasure getRoundingRadius()
	{
		return this.RoundingRadius;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	public Object clone()
	{
		IfcRoundedRectangleProfileDef ifcRoundedRectangleProfileDef = new IfcRoundedRectangleProfileDef();
		if(this.ProfileType != null)
			ifcRoundedRectangleProfileDef.setProfileType((IfcProfileTypeEnum)this.ProfileType.clone());
		if(this.ProfileName != null)
			ifcRoundedRectangleProfileDef.setProfileName((IfcLabel)this.ProfileName.clone());
		if(this.Position != null)
			ifcRoundedRectangleProfileDef.setPosition((IfcAxis2Placement2D)this.Position.clone());
		if(this.XDim != null)
			ifcRoundedRectangleProfileDef.setXDim((IfcPositiveLengthMeasure)this.XDim.clone());
		if(this.YDim != null)
			ifcRoundedRectangleProfileDef.setYDim((IfcPositiveLengthMeasure)this.YDim.clone());
		if(this.RoundingRadius != null)
			ifcRoundedRectangleProfileDef.setRoundingRadius((IfcPositiveLengthMeasure)this.RoundingRadius.clone());
		return ifcRoundedRectangleProfileDef;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcRoundedRectangleProfileDef ifcRoundedRectangleProfileDef = new IfcRoundedRectangleProfileDef();
		if(this.ProfileType != null)
			ifcRoundedRectangleProfileDef.setProfileType(this.ProfileType);
		if(this.ProfileName != null)
			ifcRoundedRectangleProfileDef.setProfileName(this.ProfileName);
		if(this.Position != null)
			ifcRoundedRectangleProfileDef.setPosition(this.Position);
		if(this.XDim != null)
			ifcRoundedRectangleProfileDef.setXDim(this.XDim);
		if(this.YDim != null)
			ifcRoundedRectangleProfileDef.setYDim(this.YDim);
		if(this.RoundingRadius != null)
			ifcRoundedRectangleProfileDef.setRoundingRadius(this.RoundingRadius);
		return ifcRoundedRectangleProfileDef;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
