/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc2x3javatoolbox.ifc2x3tc1;
/**
 * This is a default implementation of the entity IfcSurfaceStyleWithTextures<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcSurfaceStyleWithTextures extends InternalAccessClass implements ClassInterface, IfcSurfaceStyleElementSelect
{
	private static final String[] nonInverseAttributes = new String[]{"LIST<IfcSurfaceTexture>"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** Textures is an DEMANDED attribute - may not be null**/
	protected LIST<IfcSurfaceTexture> Textures;
	/**
	* The default constructor.
	**/
	public IfcSurfaceStyleWithTextures(){}

	private static final String[] attributes = new String[]{"Textures"};

	public String[] getAttributes(){
		return IfcSurfaceStyleWithTextures.attributes;
	}


	/**
	* Constructs a new IfcSurfaceStyleWithTextures object using the given parameters.
	*
	* @param Textures DEMANDED parameter of type LIST<IfcSurfaceTexture> - may not be null.
	**/
	public IfcSurfaceStyleWithTextures(LIST<IfcSurfaceTexture> Textures)
	{
		this.Textures = Textures;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcSurfaceStyleWithTextures object using the given parameters.
	*
	* @param Textures DEMANDED parameter of type LIST<IfcSurfaceTexture> - may not be null.
	**/
	public void setParameters(LIST<IfcSurfaceTexture> Textures)
	{
		this.Textures = Textures;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	@SuppressWarnings("unchecked")
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.Textures = (LIST<IfcSurfaceTexture>) parameters.get(0);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		listenerList = null;
	}

	private void resolveInverses()
	{
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcSurfaceStyleWithTextures.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCSURFACESTYLEWITHTEXTURES(");
		if(getRedefinedDerivedAttributeTypes().contains("Textures")) stepString = stepString.concat("*);");
		else{
		if(this.Textures != null)		stepString = stepString.concat(((RootInterface)this.Textures).getStepParameter(IfcSurfaceTexture.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method sets the Textures attribute to the given value.
	*
	* @param Textures OPTIONAL value to set
	**/
	public void setTextures(LIST<IfcSurfaceTexture> Textures)
	{
		this.Textures = Textures;
		fireChangeEvent();
	}

	/**
	* This method returns a copy of the list of the Textures attribute.
	*
	* @return a copy of the Textures list
	**/
	public LIST<IfcSurfaceTexture> getTextures()
	{
		if(this.Textures != null)
			return new LIST<IfcSurfaceTexture>(this.Textures);
		return null;
	}

	/**
	* This method adds an IfcSurfaceTexture object to the Textures list.
	* @param Textures element to be appended to this list.
	**/
	public void addTextures(IfcSurfaceTexture Textures)
	{
		if(this.Textures == null)
			this.Textures = new LIST<IfcSurfaceTexture>();
		this.Textures.add(Textures);
		fireChangeEvent();
	}

	/**
	* This method adds a collection of IfcSurfaceTexture objects to the Textures list.
	* @param Textures collection containing elements to be added to this list.
	**/
	public void addAllTextures(java.util.Collection<IfcSurfaceTexture> Textures)
	{
		if(this.Textures == null)
			this.Textures = new LIST<IfcSurfaceTexture>();
		this.Textures.addAll(Textures);
		fireChangeEvent();
	}

	/**
	* This method removes all elements from the Textures list.
	**/
	public void clearTextures()
	{
		if(this.Textures != null)
		{
			this.Textures.clear();
			fireChangeEvent();
		}
	}

	/**
	* This method removes an IfcSurfaceTexture object from the Textures list.
	* @param Textures element to be removed from this list.
	**/
	public void removeTextures(IfcSurfaceTexture Textures)
	{
		if(this.Textures != null)
		{
			this.Textures.remove(Textures);
			fireChangeEvent();
		}
	}

	/**
	* This method removes a collection of IfcSurfaceTexture objects from the Textures list.
	* @param Textures collection containing elements to be removed from this list.
	**/
	public void removeAllTextures(java.util.Collection<IfcSurfaceTexture> Textures)
	{
		if(this.Textures != null)
		{
			this.Textures.removeAll(Textures);
			fireChangeEvent();
		}
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	@SuppressWarnings("unchecked")
	public Object clone()
	{
		IfcSurfaceStyleWithTextures ifcSurfaceStyleWithTextures = new IfcSurfaceStyleWithTextures();
		if(this.Textures != null)
			ifcSurfaceStyleWithTextures.setTextures((LIST<IfcSurfaceTexture>)this.Textures.clone());
		return ifcSurfaceStyleWithTextures;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcSurfaceStyleWithTextures ifcSurfaceStyleWithTextures = new IfcSurfaceStyleWithTextures();
		if(this.Textures != null)
			ifcSurfaceStyleWithTextures.setTextures(this.Textures);
		return ifcSurfaceStyleWithTextures;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
