/* Generated By: IFC Tools Project EXPRESS TO JAVA COMPILER: Do not edit this file!! */
package ifc2x3javatoolbox.ifc2x3tc1;
/**
 * This is a default implementation of the entity IfcVertexLoop<br><br>
 *<br><br>
 * Copyright: CC BY-NC-SA 3.0 DE (cc) 2013 Eike Tauscher and Michael Theiler<br><br>
 * The whole package including this class is licensed under<br>
 * <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en/'>
 * Creative Commons Attribution-Non-Commercial-Share Alike 3.0 Germany</a>.<br><br>
 * If you are using the package or parts of it in any commercial way, a commercial license is required. 
 * Visit <a href='http://www.ifctoolsproject.com'>http://www.ifctoolsproject.com</a> for more information
 * or contact us directly: <a href='mailto:info@ifctoolsproject.com'>info@ifctoolsproject.com</a><br>
 */
public class IfcVertexLoop extends IfcLoop implements ClassInterface
{
	private static final String[] nonInverseAttributes = new String[]{"IfcVertex"};
	private java.util.ArrayList<CloneableObject> stepParameter = null;
	private java.util.HashSet<ObjectChangeListener> listenerList = null;
	protected int stepLineNumber;
	/** LoopVertex is an DEMANDED attribute - may not be null**/
	protected IfcVertex LoopVertex;
	/**
	* The default constructor.
	**/
	public IfcVertexLoop(){}

	private static final String[] attributes = new String[]{"LoopVertex"};

	public String[] getAttributes(){
		return IfcVertexLoop.attributes;
	}

	/**
	* Constructs a new IfcVertexLoop object using the given parameters.
	*
	* @param LoopVertex DEMANDED parameter of type IfcVertex - may not be null.
	**/
	public IfcVertexLoop(IfcVertex LoopVertex)
	{
		this.LoopVertex = LoopVertex;
		resolveInverses();
	}

	/**
	 * This method initializes the IfcVertexLoop object using the given parameters.
	*
	* @param LoopVertex DEMANDED parameter of type IfcVertex - may not be null.
	**/
	public void setParameters(IfcVertex LoopVertex)
	{
		this.LoopVertex = LoopVertex;
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void initialize(java.util.ArrayList<CloneableObject> parameters)
	{
		this.LoopVertex = (IfcVertex) parameters.get(0);
		resolveInverses();
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void destruct()
	{
		 super.destruct();
		listenerList = null;
	}

	private void resolveInverses()
	{
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	String[] getNonInverseAttributeTypes()
	{
		return IfcVertexLoop.nonInverseAttributes;	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	private java.util.HashSet<String> getRedefinedDerivedAttributeTypes()
	{
		java.util.HashSet<String> redefinedDerivedAttributes = new java.util.HashSet<String>();
		return redefinedDerivedAttributes;	}

	/**
 * This method returns the object IFC  STEP representation. This method is called by the IfcModel object to write IFC STEP files.
	 *
	 * @return the IFC STEP representation of this object
	**/
	public String getStepLine()
	{
		String stepString = new String("#"+this.stepLineNumber+"= ");
		stepString = stepString.concat("IFCVERTEXLOOP(");
		if(getRedefinedDerivedAttributeTypes().contains("LoopVertex")) stepString = stepString.concat("*);");
		else{
		if(this.LoopVertex != null)		stepString = stepString.concat(((RootInterface)this.LoopVertex).getStepParameter(IfcVertex.class.isInterface())+");");
		else		stepString = stepString.concat("$);");
		}
		return stepString;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	public String getStepParameter(boolean isSelectType)
	{
		return "#" + this.stepLineNumber;
	}

	/**
	 * This method returns the line number within a IFC  STEP representation. This method is called from other objects, where this one is referenced.
	 *
	 * @return the STEP line number
	**/
	public int getStepLineNumber()
	{
		return this.stepLineNumber;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepLineNumber(int number)
	{
		this.stepLineNumber = number;
	}

	/**
	* This method sets the LoopVertex attribute to the given value.
	*
	* @param LoopVertex OPTIONAL value to set
	**/
	public void setLoopVertex(IfcVertex LoopVertex)
	{
		this.LoopVertex = LoopVertex;
		fireChangeEvent();
	}

	/**
	* This method returns the value of the LoopVertex attribute.
	*
	* @return the value of LoopVertex
	/**/
	public IfcVertex getLoopVertex()
	{
		return this.LoopVertex;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	void setStepParameter(java.util.ArrayList<CloneableObject> parameter)
	{
		this.stepParameter = parameter;
	}

	/**
	 * This method is used internally and should NOT be used for own purposes.
	**/
	java.util.ArrayList<CloneableObject> getStepParameter()
	{
		return this.stepParameter;
	}

	/**
	 * This method registers an ObjectChangeListener to this object. An event is fired whenever one of its values was changed.
	 * 
	 *@param listener the listener to register
	**/
	public void addObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	listenerList = new java.util.HashSet<ObjectChangeListener>(1,1);
		listenerList.add(listener);
	}

	/**
	 * This method unregisters an ObjectChangeListener from this object.
	 * 
	 *@param listener the listener to unregister
	**/
	public void removeObjectChangeListener(ObjectChangeListener listener)
	{
		if (listenerList == null)	return;
		listenerList.remove(listener);
		if (listenerList.size()==0) listenerList = null;
	}

	/**
	 * This method removes all currently registered ObjectChangeListeners from this object.
	**/
	public void removeAllObjectChangeListeners()
	{
		listenerList = null;
	}

	protected void fireChangeEvent()
	{
		if(listenerList == null) return;
		for(ObjectChangeListener listener : listenerList)
			listener.ifcModelObjectChange(this);
	}

	/**
	 * This method clones the object (deep cloning).
	 *
	 * @return the cloned object
	**/
	public Object clone()
	{
		IfcVertexLoop ifcVertexLoop = new IfcVertexLoop();
		if(this.LoopVertex != null)
			ifcVertexLoop.setLoopVertex((IfcVertex)this.LoopVertex.clone());
		return ifcVertexLoop;
	}

	/**
	 * This method copys the object as shallow copy (all referenced objects are remaining).
	 *
	 * @return the cloned object
	**/
	public Object shallowCopy()
	{
		IfcVertexLoop ifcVertexLoop = new IfcVertexLoop();
		if(this.LoopVertex != null)
			ifcVertexLoop.setLoopVertex(this.LoopVertex);
		return ifcVertexLoop;
	}

	/**
	* This method returns the objects standard description.
	*
	* @return the standard description
	**/
	public String toString()
	{
		return "#"+ this.getStepLineNumber() + " " + this.getClass().getSimpleName();
	}


}
